### ISSUE TITLE
Need light theme on https://ecoji.dev/

### ISSUE THREAD

**Issue by sandyarmstrong** [abock/dotnet-ecoji#1]
In the year 2020, it is hard to take a corporation seriously if it does not offer its customers a light themed website. The benefits of light themes were known by the ancient philosophers to improve one's virility and avoid the serious risks associated with exposure to dark themes, such as premature opening of the third eye.

I'm afraid I cannot make an investment in this venture until you take steps to address this concern.

Looking forward to hearing from you,
Sandy

**Comment by abock** [comment]
@sandyarmstrong if you are willing to financially invest in this space we can definitely write the CSS for you.

**Comment by abock** [comment]
Closing this. The team has not received a sufficient response in the form of financial investment.
