### ISSUE TITLE
RoundTripFile - Tests - Fail

### ISSUE THREAD

**Issue by garciaolais** [abock/dotnet-ecoji#2]
Hi

I have an issue when running `dotnet test`

5  _RoundTripFile_ tests doesn't pass  

❌ -  LoremIpsum 
![image](https://user-images.githubusercontent.com/14133711/84585890-efbef880-add9-11ea-89ce-1b7239955a8d.png)
❌ - RandomAligned
![image](https://user-images.githubusercontent.com/14133711/84585884-e2097300-add9-11ea-9227-f5b8c61b5e4e.png)
❌ - RandomUnaligned1
![image](https://user-images.githubusercontent.com/14133711/84585893-fd747e00-add9-11ea-9260-2047937fcfae.png)
❌ - RandomUnaligned2
![image](https://user-images.githubusercontent.com/14133711/84585898-05ccb900-adda-11ea-866b-121826426b25.png)
❌ - RandomUnaligned3
![image](https://user-images.githubusercontent.com/14133711/84585877-ca31ef00-add9-11ea-8257-8eb0339e3d05.png)

**Comment by abock** [comment]
Should be fixed now. The tests force `\n` now since the reference data was encoded on macOS.
